name: InventoryCommands
version: ${project.version}
description: Genesis Addon - Allows opening GUIs in new ways
author: Black_ixx,MageMonkeyStudios
website: http://felix.neuby.de
main: studio.magemonkey.genesis.addon.inventorycommands.InventoryCommands
depend: [Genesis]
commands:
  gsm:
   description: InventoryCommands command