name: InventoryCommands
version: ${project.version}
description: Genesis Addon - Allows opening GUIs in new ways
author: Black_ixx,ProMCTeam
website: http://felix.neuby.de
main: com.promcteam.genesis.addon.guishopmanager.GuiShopManager
depend: [Genesis]
commands:
  gsm:
   description: InventoryCommands command